### PR TITLE
Add eslint config & test

### PR DESCRIPTION
**Pull request by VivekSingh777**

### CODE REVIEW

**Comment by VivekSingh777** [comment]
@MattIPv4 Added eslint support

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
1. Indentation in the config file is inconsistent.
2. Can we use strings for off/warn/error instead of their integer counterparts?
3. Can eslint also be integrated into the mocha test suite, please?

**Comment by VivekSingh777** [comment]
Screenshot 2019-10-09 at 4 10 06 AM
@MattIPv4 Did I need to fix all lint errors?

**Comment by MattIPv4** [comment]
No, don’t worry about fixing the errors, that can be a separate issue once this is merged — However, is there a config change that can be made to resolve window & document being undefined being treated as an issue?

**Comment by VivekSingh777** [comment]
> No, don’t worry about fixing the errors, that can be a separate issue once this is merged — However, is there a config change that can be made to resolve window & document being undefined being treated as an issue?

> 1. Indentation in the config file is inconsistent.
> 2. Can we use strings for off/warn/error instead of their integer counterparts?
> 3. Can eslint also be integrated into the mocha test suite, please?

@MattIPv4 Done

**Comment by VivekSingh777** [comment]
@MattIPv4 Done changes and integrated eslint to mocha

**Comment by MattIPv4** [comment]
If this was integrated into the mocha test suite, should the CI have failed as there are outstanding eslint issues with the project?

**Comment by MattIPv4** [comment]
Oops.

**Comment by VivekSingh777** [comment]
> If this was integrated into the mocha test suite, should the CI have failed as there are outstanding eslint issues with the project?

I don't get it?

**Comment by MattIPv4** [comment]
The CI runs `npm test` which is the full mocha test suite, located in the `/test` directory. The eslint checks should be added so that they run as part of the mocha test suite, please :)

I can help with this in the morning if you’re stuck or unsure.

**Comment by VivekSingh777** [comment]
Cool will take this up in morning.

**Comment by VivekSingh777** [comment]
> The CI runs `npm test` which is the full mocha test suite, located in the `/test` directory. The eslint checks should be added so that they run as part of the mocha test suite, please :)
> 
> I can help with this in the morning if you’re stuck or unsure.

Can u help me about your comment.
I have integrated eslint with mocha. Here is the screenshot for the same.
Screenshot 2019-10-09 at 11 32 35 AM
@MattIPv4

**Comment by MattIPv4** [comment]
CI failure expected.

**Review by MattIPv4 — APPROVED** [review]
Lgtm.

**Pull request merged**
