### PR TITLE
Style & branding changes

### PR DESCRIPTION
**Pull request by MattIPv4**

### CODE REVIEW

**Review by Andre601 — APPROVED** [review]

**Comment by Andre601** [comment]
CI still seems to not like it.

**Review by jacobmitchell04 — APPROVED** [review]
Looks good.

**Comment by MattIPv4** [comment]
No idea why this spec is failing, this PR hasn't touched the API. Cannot reproduce the failure locally either.

**Review by Andre601 — APPROVED** [review]

**Comment by Andre601** [comment]
Why does my approval (which was requested) not count to the approvals? 🤔

**Comment by MattIPv4** [comment]
You don't have write access

**Pull request merged**
